jwt:
  secret: bXktc3RyaW5n;

server:
  port: 8083
spring:
  application:
    name: auth-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
user:
  service:
    url: http://localhost:9099

billing:
  service:
    url: http://localhost:8082

management:
  server:
    port: 7081
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    db:
      enabled: true
  metrics:
    distribution:
      slo:
        http:
          server:
            requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
  prometheus:
    metrics:
      export:
        enabled: true