apiVersion: v1
kind: Secret
metadata:
  name: db-secret-user
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.auth.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.auth.password }}"
