apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config-auth
data:
  application.yaml: |
    jwt:
      secret: ${JWT_SECRET}
    server:
      port: 8080
    spring:
      jpa:
        hibernate:
          ddl-auto: update
    user:
      service:
        url: http://user-app-service.{{ .Release.Namespace }}.svc.cluster.local

    billing:
      service:
        url: http://billing-app-service.{{ .Release.Namespace }}.svc.cluster.local

    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      prometheus:
        metrics:
          export:
            enabled: true
      metrics:
        distribution:
          slo:
            http:
              server:
                requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms