apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  application.yaml: |
    server:
      port: 8082
    spring:
      jpa:
        hibernate:
          ddl-auto: update

    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      prometheus:
        metrics:
          export:
            enabled: true
      metrics:
        distribution:
          slo:
            http:
              server:
                requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms