container:
  image: jen1g/delivery
  tag: v1
  port: 8080


postgresql:
  auth:
    postgresPassword: "12345"
    username: "pguser"
    password: "12345"
    database: "delivery_service_db"
  persistence:
    enabled: true
    storageClass: "standard" # kubectl get sc
    accessModes:
      - ReadWriteOnce
    size: 2Gi