server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: http://localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

billing:
  service:
    url: http://localhost:8082

delivery:
  service:
    url: http://localhost:8086

warehouse:
  service:
    url: http://localhost:8087

payment:
  service:
    url: http://localhost:8084

management:
  server:
    port: 7086
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    db:
      enabled: true
  metrics:
    distribution:
      slo:
        http:
          server:
            requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
  prometheus:
    metrics:
      export:
        enabled: true



