apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  application.yaml: |
    spring:
      kafka:
        bootstrap-servers: http://kafka.otus.svc.cluster.local:9092
      jpa:
        hibernate:
          ddl-auto: update

    billing:
      service:
        url: http://billing-app-service.{{ .Release.Namespace }}.svc.cluster.local

    delivery:
      service:
        url: http://delivery-app-service.{{ .Release.Namespace }}.svc.cluster.local

    warehouse:
      service:
        url: http://warehouse-app-service.{{ .Release.Namespace }}.svc.cluster.local

    payment:
      service:
        url: http://payment-app-service.{{ .Release.Namespace }}.svc.cluster.local


    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      prometheus:
        metrics:
          export:
            enabled: true
      metrics:
        distribution:
          slo:
            http:
              server:
                requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
